// spotless hungry crocodile-angular/src/app/components/banner2/banner2.component.ts
import { Component, Input, ContentChild, TemplateRef } from '@angular/core'

@Component({
  selector: 'app-banner2',
  templateUrl: 'banner2.component.html',
  styleUrls: ['banner2.component.css'],
})
export class Banner2 {
  @Input()
  video1Src: string =
    'https://videos.pexels.com/video-files/5083290/5083290-hd_2048_1080_25fps.mp4'
  @ContentChild('content1')
  content1: TemplateRef<any>
  @ContentChild('action1')
  action1: TemplateRef<any>
  @ContentChild('heading1')
  heading1: TemplateRef<any>
  @Input()
  video1Poster: string =
    'https://images.pexels.com/videos/5083290/pictures/preview-0.jpg'
  constructor() {}
}

<div class="banner2-container1 thq-section-padding">
  <div class="banner2-max-width thq-section-max-width">
    <div class="banner2-container2">
      <h2 class="banner2-title thq-heading-2">
        <ng-container>
          <ng-template #defaultHeading1>
            <div class="banner2-fragment3">
              <span class="banner2-text5">
                Welcome to Smart Healthcare Portal
              </span>
            </div>
          </ng-template>
          <ng-container
            *ngTemplateOutlet="heading1 ? heading1 : defaultHeading1"
          ></ng-container>
        </ng-container>
      </h2>
      <h3 class="banner2-text1 thq-heading-3">
        <ng-container>
          <ng-template #defaultContent1>
            <div class="banner2-fragment1">
              <span class="banner2-text3">
                Your one-stop solution for all your healthcare needs
              </span>
            </div>
          </ng-template>
          <ng-container
            *ngTemplateOutlet="content1 ? content1 : defaultContent1"
          ></ng-container>
        </ng-container>
      </h3>
    </div>
    <button type="button" class="banner2-button thq-button-filled">
      <span>
        <ng-container>
          <ng-template #defaultAction1>
            <div class="banner2-fragment2">
              <span class="banner2-text4">Get Started</span>
            </div>
          </ng-template>
          <ng-container
            *ngTemplateOutlet="action1 ? action1 : defaultAction1"
          ></ng-container>
        </ng-container>
      </span>
    </button>
    <video
      [attr.src]="video1Src"
      loop="true"
      muted="true"
      [attr.poster]="video1Poster"
      autoplay="true"
      class="banner2-video"
    ></video>
  </div>
</div>

// spotless hungry crocodile-react/src/components/banner2.js
import React, { Fragment } from 'react'

import PropTypes from 'prop-types'

import './banner2.css'

const Banner2 = (props) => {
  return (
    <div className="banner2-container1 thq-section-padding">
      <div className="banner2-max-width thq-section-max-width">
        <div className="banner2-container2">
          <h2 className="banner2-title thq-heading-2">
            {props.heading1 ?? (
              <Fragment>
                <span className="banner2-text5">
                  Welcome to Smart Healthcare Portal
                </span>
              </Fragment>
            )}
          </h2>
          <h3 className="banner2-text1 thq-heading-3">
            {props.content1 ?? (
              <Fragment>
                <span className="banner2-text3">
                  Your one-stop solution for all your healthcare needs
                </span>
              </Fragment>
            )}
          </h3>
        </div>
        <button type="button" className="banner2-button thq-button-filled">
          <span>
            {props.action1 ?? (
              <Fragment>
                <span className="banner2-text4">Get Started</span>
              </Fragment>
            )}
          </span>
        </button>
        <video
          src={props.video1Src}
          loop="true"
          muted="true"
          poster={props.video1Poster}
          autoPlay="true"
          className="banner2-video"
        ></video>
      </div>
    </div>
  )
}

Banner2.defaultProps = {
  video1Src:
    'https://videos.pexels.com/video-files/5083290/5083290-hd_2048_1080_25fps.mp4',
  content1: undefined,
  action1: undefined,
  heading1: undefined,
  video1Poster:
    'https://images.pexels.com/videos/5083290/pictures/preview-0.jpg',
}

Banner2.propTypes = {
  video1Src: PropTypes.string,
  content1: PropTypes.element,
  action1: PropTypes.element,
  heading1: PropTypes.element,
  video1Poster: PropTypes.string,
}

export default Banner2
