// spotless hungry crocodile-angular/src/app/components/hero/hero.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-hero',
  templateUrl: 'hero.component.html',
  styleUrls: ['hero.component.css'],
})
export class Hero {
  @Input()
  image10Alt: string = 'Hero Image'
  @Input()
  image4Src: string =
    'https://images.unsplash.com/photo-1593491034932-844ab981ed7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Nnw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  heading1: string = 'Welcome to Smart Healthcare Portal'
  @Input()
  image4Alt: string = 'Hero Image'
  @Input()
  image1Src: string =
    'https://images.unsplash.com/photo-1539627831859-a911cf04d3cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Nnw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  image8Alt: string = 'Hero Image'
  @Input()
  image12Alt: string = 'Hero Image'
  @Input()
  image1Alt: string = 'Hero Image'
  @Input()
  image6Alt: string = 'Hero Image'
  @Input()
  image2Alt: string = 'Hero Image'
  @Input()
  image7Src: string =
    'https://images.unsplash.com/photo-1579154491915-611e891d3a5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2NHw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  image9Alt: string = 'Hero Image'
  @Input()
  image11Src: string =
    'https://images.unsplash.com/photo-1638202993928-7267aad84c31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2M3w&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  image11Alt: string = 'Hero Image'
  @Input()
  action2: string = 'Secondary action'
  @Input()
  image2Src: string =
    'https://images.unsplash.com/photo-1666887360742-974c8fce8e6b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Mnw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  image5Src: string =
    'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Nnw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  image12Src: string =
    'https://images.unsplash.com/photo-1615461066841-6116e61058f4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2NHw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  image6Src: string =
    'https://images.unsplash.com/photo-1643297654399-5da3409e302a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2NHw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  action1: string = 'Main action'
  @Input()
  content1: string =
    'Your one-stop solution for all your healthcare needs. Find doctors, book appointments, access medical records, and much more with our smart and user-friendly platform.'
  @Input()
  image9Src: string =
    'https://images.unsplash.com/photo-1666887360742-d9280ba23bd7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2NXw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  image10Src: string =
    'https://images.unsplash.com/photo-1666887360711-446ce495ce4d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Nnw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  image8Src: string =
    'https://images.unsplash.com/photo-1666887360742-974c8fce8e6b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2NXw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  image3Alt: string = 'Hero Image'
  @Input()
  image3Src: string =
    'https://images.unsplash.com/photo-1666886573199-88a2ed65470d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2MXw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  image7Alt: string = 'Hero Image'
  @Input()
  image5Alt: string = 'Hero Image'
  constructor() {}
}

<div class="hero-header78">
  <div class="hero-column thq-section-padding thq-section-max-width">
    <div class="hero-content1">
      <h1 class="hero-text1 thq-heading-1">{{ heading1 }}</h1>
      <p class="hero-text2 thq-body-large">{{ content1 }}</p>
    </div>
    <div class="hero-actions">
      <button class="thq-button-filled hero-button1">
        <span class="thq-body-small">{{ action1 }}</span>
      </button>
      <button class="thq-button-outline hero-button2">
        <span class="thq-body-small">{{ action2 }}</span>
      </button>
    </div>
  </div>
  <div class="hero-content2">
    <div
      class="hero-row-container1 thq-mask-image-horizontal thq-animated-group-container-horizontal"
    >
      <div class="thq-animated-group-horizontal">
        <img
          [attr.alt]="image1Alt"
          [attr.src]="image1Src"
          class="hero-placeholder-image10 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image2Alt"
          [attr.src]="image2Src"
          class="hero-placeholder-image11 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image3Alt"
          [attr.src]="image3Src"
          class="hero-placeholder-image12 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image4Alt"
          [attr.src]="image4Src"
          class="hero-placeholder-image13 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image5Alt"
          [attr.src]="image5Src"
          class="hero-placeholder-image14 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image6Alt"
          [attr.src]="image6Src"
          class="hero-placeholder-image15 thq-img-ratio-1-1 thq-img-scale"
        />
      </div>
      <div class="thq-animated-group-horizontal">
        <img
          [attr.alt]="image1Alt"
          [attr.src]="image1Src"
          class="hero-placeholder-image16 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image2Alt"
          [attr.src]="image2Src"
          class="hero-placeholder-image17 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image3Alt"
          [attr.src]="image3Src"
          class="hero-placeholder-image18 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image4Alt"
          [attr.src]="image4Src"
          class="hero-placeholder-image19 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image5Alt"
          [attr.src]="image5Src"
          class="hero-placeholder-image20 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          alt="Hero Image"
          src="https://images.unsplash.com/photo-1534312527009-56c7016453e6?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDIxfHxhYnN0cmFjdHxlbnwwfHx8fDE3MTA4NzA5MzB8MA&amp;ixlib=rb-4.0.3&amp;w=1500"
          class="hero-placeholder-image21 thq-img-ratio-1-1 thq-img-scale"
        />
      </div>
    </div>
    <div
      class="hero-row-container2 thq-mask-image-horizontal thq-animated-group-container-horizontal"
    >
      <div class="thq-animated-group-horizontal-reverse">
        <img
          [attr.alt]="image7Alt"
          [attr.src]="image7Src"
          class="hero-placeholder-image22 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image8Alt"
          [attr.src]="image8Src"
          class="hero-placeholder-image23 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image9Alt"
          [attr.src]="image9Src"
          class="hero-placeholder-image24 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image10Alt"
          [attr.src]="image10Src"
          class="hero-placeholder-image25 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image11Alt"
          [attr.src]="image11Src"
          class="hero-placeholder-image26 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image12Alt"
          [attr.src]="image12Src"
          class="hero-placeholder-image27 thq-img-ratio-1-1 thq-img-scale"
        />
      </div>
      <div class="thq-animated-group-horizontal-reverse">
        <img
          [attr.alt]="image7Alt"
          [attr.src]="image7Src"
          class="hero-placeholder-image28 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image8Alt"
          [attr.src]="image8Src"
          class="hero-placeholder-image29 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image9Alt"
          [attr.src]="image9Src"
          class="hero-placeholder-image30 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image10Alt"
          [attr.src]="image10Src"
          class="hero-placeholder-image31 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          [attr.alt]="image11Alt"
          [attr.src]="image11Src"
          class="hero-placeholder-image32 thq-img-ratio-1-1 thq-img-scale"
        />
        <img
          alt="Hero Image"
          src="https://images.unsplash.com/photo-1568214379698-8aeb8c6c6ac8?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDEyfHxncmFmaWN8ZW58MHx8fHwxNzE1Nzk0OTk5fDA&amp;ixlib=rb-4.0.3&amp;w=1500"
          class="hero-placeholder-image33 thq-img-ratio-1-1 thq-img-scale"
        />
      </div>
    </div>
  </div>
  <div>
    <div class="hero-container2">
      <style>
        @keyframes scroll-x {
          from {
            transform: translateX(0);
          }
          to {
            transform: translateX(calc(-100% - 16px));
          }
        }

        @keyframes scroll-y {
          from {
            transform: translateY(0);
          }
          to {
            transform: translateY(calc(-100% - 16px));
          }
        }
      </style>
    </div>
  </div>
</div>

// spotless hungry crocodile-react/src/components/hero.js
import React from 'react'

import Script from 'dangerous-html/react'
import PropTypes from 'prop-types'

import './hero.css'

const Hero = (props) => {
  return (
    <div className="hero-header78">
      <div className="hero-column thq-section-padding thq-section-max-width">
        <div className="hero-content1">
          <h1 className="hero-text1 thq-heading-1">{props.heading1}</h1>
          <p className="hero-text2 thq-body-large">{props.content1}</p>
        </div>
        <div className="hero-actions">
          <button className="thq-button-filled hero-button1">
            <span className="thq-body-small">{props.action1}</span>
          </button>
          <button className="thq-button-outline hero-button2">
            <span className="thq-body-small">{props.action2}</span>
          </button>
        </div>
      </div>
      <div className="hero-content2">
        <div className="hero-row-container1 thq-mask-image-horizontal thq-animated-group-container-horizontal">
          <div className="thq-animated-group-horizontal">
            <img
              alt={props.image1Alt}
              src={props.image1Src}
              className="hero-placeholder-image10 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image2Alt}
              src={props.image2Src}
              className="hero-placeholder-image11 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image3Alt}
              src={props.image3Src}
              className="hero-placeholder-image12 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image4Alt}
              src={props.image4Src}
              className="hero-placeholder-image13 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image5Alt}
              src={props.image5Src}
              className="hero-placeholder-image14 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image6Alt}
              src={props.image6Src}
              className="hero-placeholder-image15 thq-img-ratio-1-1 thq-img-scale"
            />
          </div>
          <div className="thq-animated-group-horizontal">
            <img
              alt={props.image1Alt}
              src={props.image1Src}
              className="hero-placeholder-image16 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image2Alt}
              src={props.image2Src}
              className="hero-placeholder-image17 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image3Alt}
              src={props.image3Src}
              className="hero-placeholder-image18 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image4Alt}
              src={props.image4Src}
              className="hero-placeholder-image19 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image5Alt}
              src={props.image5Src}
              className="hero-placeholder-image20 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt="Hero Image"
              src="https://images.unsplash.com/photo-1534312527009-56c7016453e6?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDIxfHxhYnN0cmFjdHxlbnwwfHx8fDE3MTA4NzA5MzB8MA&amp;ixlib=rb-4.0.3&amp;w=1500"
              className="hero-placeholder-image21 thq-img-ratio-1-1 thq-img-scale"
            />
          </div>
        </div>
        <div className="hero-row-container2 thq-mask-image-horizontal thq-animated-group-container-horizontal">
          <div className="thq-animated-group-horizontal-reverse">
            <img
              alt={props.image7Alt}
              src={props.image7Src}
              className="hero-placeholder-image22 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image8Alt}
              src={props.image8Src}
              className="hero-placeholder-image23 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image9Alt}
              src={props.image9Src}
              className="hero-placeholder-image24 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image10Alt}
              src={props.image10Src}
              className="hero-placeholder-image25 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image11Alt}
              src={props.image11Src}
              className="hero-placeholder-image26 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image12Alt}
              src={props.image12Src}
              className="hero-placeholder-image27 thq-img-ratio-1-1 thq-img-scale"
            />
          </div>
          <div className="thq-animated-group-horizontal-reverse">
            <img
              alt={props.image7Alt}
              src={props.image7Src}
              className="hero-placeholder-image28 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image8Alt}
              src={props.image8Src}
              className="hero-placeholder-image29 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image9Alt}
              src={props.image9Src}
              className="hero-placeholder-image30 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image10Alt}
              src={props.image10Src}
              className="hero-placeholder-image31 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt={props.image11Alt}
              src={props.image11Src}
              className="hero-placeholder-image32 thq-img-ratio-1-1 thq-img-scale"
            />
            <img
              alt="Hero Image"
              src="https://images.unsplash.com/photo-1568214379698-8aeb8c6c6ac8?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDEyfHxncmFmaWN8ZW58MHx8fHwxNzE1Nzk0OTk5fDA&amp;ixlib=rb-4.0.3&amp;w=1500"
              className="hero-placeholder-image33 thq-img-ratio-1-1 thq-img-scale"
            />
          </div>
        </div>
      </div>
      <div>
        <div className="hero-container2">
          <React.Fragment>
            <React.Fragment>
              <style
                dangerouslySetInnerHTML={{
                  __html:
                    '\n  @keyframes scroll-x {\n    from {\n      transform: translateX(0);\n    }\n    to {\n      transform: translateX(calc(-100% - 16px));\n    }\n  }\n\n  @keyframes scroll-y {\n    from {\n      transform: translateY(0);\n    }\n    to {\n      transform: translateY(calc(-100% - 16px));\n    }\n  }\n',
                }}
              />
            </React.Fragment>
          </React.Fragment>
        </div>
      </div>
    </div>
  )
}

Hero.defaultProps = {
  image10Alt: 'Hero Image',
  image4Src:
    'https://images.unsplash.com/photo-1593491034932-844ab981ed7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Nnw&ixlib=rb-4.0.3&q=80&w=1080',
  heading1: 'Welcome to Smart Healthcare Portal',
  image4Alt: 'Hero Image',
  image1Src:
    'https://images.unsplash.com/photo-1539627831859-a911cf04d3cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Nnw&ixlib=rb-4.0.3&q=80&w=1080',
  image8Alt: 'Hero Image',
  image12Alt: 'Hero Image',
  image1Alt: 'Hero Image',
  image6Alt: 'Hero Image',
  image2Alt: 'Hero Image',
  image7Src:
    'https://images.unsplash.com/photo-1579154491915-611e891d3a5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2NHw&ixlib=rb-4.0.3&q=80&w=1080',
  image9Alt: 'Hero Image',
  image11Src:
    'https://images.unsplash.com/photo-1638202993928-7267aad84c31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2M3w&ixlib=rb-4.0.3&q=80&w=1080',
  image11Alt: 'Hero Image',
  action2: 'Secondary action',
  image2Src:
    'https://images.unsplash.com/photo-1666887360742-974c8fce8e6b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Mnw&ixlib=rb-4.0.3&q=80&w=1080',
  image5Src:
    'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Nnw&ixlib=rb-4.0.3&q=80&w=1080',
  image12Src:
    'https://images.unsplash.com/photo-1615461066841-6116e61058f4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2NHw&ixlib=rb-4.0.3&q=80&w=1080',
  image6Src:
    'https://images.unsplash.com/photo-1643297654399-5da3409e302a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2NHw&ixlib=rb-4.0.3&q=80&w=1080',
  action1: 'Main action',
  content1:
    'Your one-stop solution for all your healthcare needs. Find doctors, book appointments, access medical records, and much more with our smart and user-friendly platform.',
  image9Src:
    'https://images.unsplash.com/photo-1666887360742-d9280ba23bd7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2NXw&ixlib=rb-4.0.3&q=80&w=1080',
  image10Src:
    'https://images.unsplash.com/photo-1666887360711-446ce495ce4d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Nnw&ixlib=rb-4.0.3&q=80&w=1080',
  image8Src:
    'https://images.unsplash.com/photo-1666887360742-974c8fce8e6b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2NXw&ixlib=rb-4.0.3&q=80&w=1080',
  image3Alt: 'Hero Image',
  image3Src:
    'https://images.unsplash.com/photo-1666886573199-88a2ed65470d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2MXw&ixlib=rb-4.0.3&q=80&w=1080',
  image7Alt: 'Hero Image',
  image5Alt: 'Hero Image',
}

Hero.propTypes = {
  image10Alt: PropTypes.string,
  image4Src: PropTypes.string,
  heading1: PropTypes.string,
  image4Alt: PropTypes.string,
  image1Src: PropTypes.string,
  image8Alt: PropTypes.string,
  image12Alt: PropTypes.string,
  image1Alt: PropTypes.string,
  image6Alt: PropTypes.string,
  image2Alt: PropTypes.string,
  image7Src: PropTypes.string,
  image9Alt: PropTypes.string,
  image11Src: PropTypes.string,
  image11Alt: PropTypes.string,
  action2: PropTypes.string,
  image2Src: PropTypes.string,
  image5Src: PropTypes.string,
  image12Src: PropTypes.string,
  image6Src: PropTypes.string,
  action1: PropTypes.string,
  content1: PropTypes.string,
  image9Src: PropTypes.string,
  image10Src: PropTypes.string,
  image8Src: PropTypes.string,
  image3Alt: PropTypes.string,
  image3Src: PropTypes.string,
  image7Alt: PropTypes.string,
  image5Alt: PropTypes.string,
}

export default Hero
