// spotless hungry crocodile-angular/src/app/components/testimonial/testimonial.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-testimonial',
  templateUrl: 'testimonial.component.html',
  styleUrls: ['testimonial.component.css'],
})
export class Testimonial {
  @Input()
  review1: string =
    'The Smart Healthcare Portal has revolutionized the way we manage our healthcare services. It has streamlined our processes and improved efficiency across the board.'
  @Input()
  author1Alt: string = 'Image of John Doe'
  @Input()
  author3Alt: string = 'Image of Michael Johnson'
  @Input()
  author2Name: string = 'Jane Smith'
  @Input()
  author3Position: string = 'CFO, LMN Enterprises'
  @Input()
  author1Name: string = 'John Doe'
  @Input()
  review3: string =
    'I highly recommend the Smart Healthcare Portal to any healthcare provider looking to enhance their operations. It has helped us save time and resources while improving patient care.'
  @Input()
  review2: string =
    'We have been using the Smart Healthcare Portal for a few months now, and it has exceeded our expectations. The user-friendly interface and advanced features make it a valuable tool for our organization.'
  @Input()
  author3Name: string = 'Michael Johnson'
  @Input()
  author2Src: string =
    'https://images.unsplash.com/photo-1499313843378-eebdb187f629?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Mnw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  author3Src: string =
    'https://images.unsplash.com/photo-1496203695688-3b8985780d6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Mnw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  author1Position: string = 'CEO, ABC Company'
  @Input()
  author4Position: string = 'CMO, PQR Healthcare'
  @Input()
  review4: string =
    'The Smart Healthcare Portal has been a game-changer for our organization. It has increased collaboration among our teams and improved communication with patients.'
  @Input()
  author2Position: string = 'COO, XYZ Corporation'
  @Input()
  author4Alt: string = 'Image of Sarah Williams'
  @Input()
  author4Name: string = 'Sarah Williams'
  @Input()
  content1: string =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
  @Input()
  author4Src: string =
    'https://images.unsplash.com/photo-1445282650865-52d8ea4e110b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2MXw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  author1Src: string =
    'https://images.unsplash.com/photo-1661747675166-5cf96bd5d0dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2MXw&ixlib=rb-4.0.3&q=80&w=1080'
  @Input()
  heading1: string = 'Testimonials'
  @Input()
  author2Alt: string = 'Image of Jane Smith'
  constructor() {}
}

// spotless hungry crocodile-react/src/components/testimonial.js
import React from 'react'

import PropTypes from 'prop-types'

import './testimonial.css'

const Testimonial = (props) => {
  return (
    <div className="thq-section-padding">
      <div className="testimonial-max-width thq-section-max-width">
        <div className="testimonial-container10">
          <h2 className="thq-heading-2">{props.heading1}</h2>
          <span className="testimonial-text11 thq-body-small">
            {props.content1}
          </span>
        </div>
        <div className="thq-grid-2">
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div data-animated="true" className="thq-card testimonial-card1">
                <div className="testimonial-container12">
                  <img
                    alt={props.author1Alt}
                    src={props.author1Src}
                    className="testimonial-image1"
                  />
                  <div className="testimonial-container13">
                    <strong className="thq-body-large">
                      {props.author1Name}
                    </strong>
                    <span className="thq-body-small">
                      {props.author1Position}
                    </span>
                  </div>
                </div>
                <span className="testimonial-text14 thq-body-small">
                  {props.review1}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div data-animated="true" className="thq-card testimonial-card2">
                <div className="testimonial-container14">
                  <img
                    alt={props.author2Alt}
                    src={props.author2Src}
                    className="testimonial-image2"
                  />
                  <div className="testimonial-container15">
                    <strong className="thq-body-large">
                      {props.author2Name}
                    </strong>
                    <span className="thq-body-small">
                      {props.author2Position}
                    </span>
                  </div>
                </div>
                <span className="testimonial-text17 thq-body-small">
                  {props.review2}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div data-animated="true" className="thq-card testimonial-card3">
                <div className="testimonial-container16">
                  <img
                    alt={props.author3Alt}
                    src={props.author3Src}
                    className="testimonial-image3"
                  />
                  <div className="testimonial-container17">
                    <strong className="thq-body-large">
                      {props.author3Name}
                    </strong>
                    <span className="thq-body-small">
                      {props.author3Position}
                    </span>
                  </div>
                </div>
                <span className="testimonial-text20 thq-body-small">
                  {props.review3}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div data-animated="true" className="thq-card testimonial-card4">
                <div className="testimonial-container18">
                  <img
                    alt={props.author4Alt}
                    src={props.author4Src}
                    className="testimonial-image4"
                  />
                  <div className="testimonial-container19">
                    <strong className="thq-body-large">
                      {props.author4Name}
                    </strong>
                    <span className="thq-body-small">
                      {props.author4Position}
                    </span>
                  </div>
                </div>
                <span className="testimonial-text23 thq-body-small">
                  {props.review4}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

Testimonial.defaultProps = {
  review1:
    'The Smart Healthcare Portal has revolutionized the way we manage our healthcare services. It has streamlined our processes and improved efficiency across the board.',
  author1Alt: 'Image of John Doe',
  author3Alt: 'Image of Michael Johnson',
  author2Name: 'Jane Smith',
  author3Position: 'CFO, LMN Enterprises',
  author1Name: 'John Doe',
  review3:
    'I highly recommend the Smart Healthcare Portal to any healthcare provider looking to enhance their operations. It has helped us save time and resources while improving patient care.',
  review2:
    'We have been using the Smart Healthcare Portal for a few months now, and it has exceeded our expectations. The user-friendly interface and advanced features make it a valuable tool for our organization.',
  author3Name: 'Michael Johnson',
  author2Src:
    'https://images.unsplash.com/photo-1499313843378-eebdb187f629?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Mnw&ixlib=rb-4.0.3&q=80&w=1080',
  author3Src:
    'https://images.unsplash.com/photo-1496203695688-3b8985780d6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2Mnw&ixlib=rb-4.0.3&q=80&w=1080',
  author1Position: 'CEO, ABC Company',
  author4Position: 'CMO, PQR Healthcare',
  review4:
    'The Smart Healthcare Portal has been a game-changer for our organization. It has increased collaboration among our teams and improved communication with patients.',
  author2Position: 'COO, XYZ Corporation',
  author4Alt: 'Image of Sarah Williams',
  author4Name: 'Sarah Williams',
  content1:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  author4Src:
    'https://images.unsplash.com/photo-1445282650865-52d8ea4e110b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2MXw&ixlib=rb-4.0.3&q=80&w=1080',
  author1Src:
    'https://images.unsplash.com/photo-1661747675166-5cf96bd5d0dc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMzUwMDE2MXw&ixlib=rb-4.0.3&q=80&w=1080',
  heading1: 'Testimonials',
  author2Alt: 'Image of Jane Smith',
}

Testimonial.propTypes = {
  review1: PropTypes.string,
  author1Alt: PropTypes.string,
  author3Alt: PropTypes.string,
  author2Name: PropTypes.string,
  author3Position: PropTypes.string,
  author1Name: PropTypes.string,
  review3: PropTypes.string,
  review2: PropTypes.string,
  author3Name: PropTypes.string,
  author2Src: PropTypes.string,
  author3Src: PropTypes.string,
  author1Position: PropTypes.string,
  author4Position: PropTypes.string,
  review4: PropTypes.string,
  author2Position: PropTypes.string,
  author4Alt: PropTypes.string,
  author4Name: PropTypes.string,
  content1: PropTypes.string,
  author4Src: PropTypes.string,
  author1Src: PropTypes.string,
  heading1: PropTypes.string,
  author2Alt: PropTypes.string,
}

export default Testimonial
