// spotless hungry crocodile-react/src/components/cta.js
import React from 'react'

import PropTypes from 'prop-types'

import './cta.css'

const CTA = (props) => {
  return (
    <div className="thq-section-padding">
      <div className="thq-section-max-width">
        <div className="cta-accent2-bg">
          <div className="cta-accent1-bg">
            <div className="cta-container2">
              <div className="cta-content">
                <span className="thq-heading-2">{props.heading1}</span>
                <p className="thq-body-large">{props.content1}</p>
              </div>
              <div className="cta-actions">
                <button type="button" className="thq-button-filled cta-button">
                  {props.action1}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

CTA.defaultProps = {
  content1: 'Experience the future of healthcare with our innovative platform.',
  action1: 'Sign Up Now',
  heading1: 'Join Our Smart Healthcare Portal Today',
}

CTA.propTypes = {
  content1: PropTypes.string,
  action1: PropTypes.string,
  heading1: PropTypes.string,
}

export default CTA

// spotless hungry crocodile-angular/src/app/components/cta/cta.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-cta',
  templateUrl: 'cta.component.html',
  styleUrls: ['cta.component.css'],
})
export class CTA {
  @Input()
  content1: string =
    'Experience the future of healthcare with our innovative platform.'
  @Input()
  action1: string = 'Sign Up Now'
  @Input()
  heading1: string = 'Join Our Smart Healthcare Portal Today'
  constructor() {}
}
