// spotless hungry crocodile-react/src/views/home.js
import React, { Fragment } from 'react'

import { DateTimePrimitive } from '@teleporthq/react-components'
import { Helmet } from 'react-helmet'

import Navbar from '../components/navbar'
import Banner2 from '../components/banner2'
import Hero from '../components/hero'
import Features1 from '../components/features1'
import CTA from '../components/cta'
import Features2 from '../components/features2'
import Pricing from '../components/pricing'
import Steps from '../components/steps'
import Testimonial from '../components/testimonial'
import Contact from '../components/contact'
import Footer from '../components/footer'
import './home.css'

const Home = (props) => {
  return (
    <div className="home-container">
      <Helmet>
        <title>Spotless Hungry Crocodile</title>
      </Helmet>
      <Navbar></Navbar>
      <Banner2
        action1={
          <Fragment>
            <span className="home-text1">Get Started</span>
          </Fragment>
        }
        content1={
          <Fragment>
            <span className="home-text2">
              Your one-stop solution for all your healthcare needs
            </span>
          </Fragment>
        }
        heading1={
          <Fragment>
            <span className="home-text3">
              Welcome to Smart Healthcare Portal
            </span>
          </Fragment>
        }
      ></Banner2>
      <Hero></Hero>
      <span>
        <DateTimePrimitive
          format="DD/MM/YYYY"
          date="Fri Dec 06 2024 20:50:28 GMT+0500 (Pakistan Standard Time)"
        ></DateTimePrimitive>
      </span>
      <Features1></Features1>
      <CTA></CTA>
      <Features2></Features2>
      <Pricing></Pricing>
      <Steps></Steps>
      <Testimonial></Testimonial>
      <Contact></Contact>
      <Footer></Footer>
    </div>
  )
}

export default Home

// spotless hungry crocodile-vue/src/views/home.vue
<template>
  <div class="home-container">
    <app-navbar></app-navbar>
    <app-banner2>
      <template v-slot:action1>
        <div class="home-fragment1">
          <span class="home-text1">Get Started</span>
        </div>
      </template>
      <template v-slot:content1>
        <div class="home-fragment2">
          <span class="home-text2">
            Your one-stop solution for all your healthcare needs
          </span>
        </div>
      </template>
      <template v-slot:heading1>
        <div class="home-fragment3">
          <span class="home-text3">Welcome to Smart Healthcare Portal</span>
        </div>
      </template>
    </app-banner2>
    <app-hero></app-hero>
    <span>
      <DateTimePrimitive
        format="DD/MM/YYYY"
        date="Fri Dec 06 2024 20:50:28 GMT+0500 (Pakistan Standard Time)"
      ></DateTimePrimitive>
    </span>
    <app-features1></app-features1>
    <app-cta></app-cta>
    <app-features2></app-features2>
    <app-pricing></app-pricing>
    <app-steps></app-steps>
    <app-testimonial></app-testimonial>
    <app-contact></app-contact>
    <app-footer></app-footer>
  </div>
</template>

<script>
import { DateTimePrimitive } from '@teleporthq/react-components'

import AppNavbar from '../components/navbar'
import AppBanner2 from '../components/banner2'
import AppHero from '../components/hero'
import AppFeatures1 from '../components/features1'
import AppCta from '../components/cta'
import AppFeatures2 from '../components/features2'
import AppPricing from '../components/pricing'
import AppSteps from '../components/steps'
import AppTestimonial from '../components/testimonial'
import AppContact from '../components/contact'
import AppFooter from '../components/footer'

export default {
  name: 'Home',
  components: {
    AppNavbar,
    AppBanner2,
    AppHero,
    DateTimePrimitive,
    AppFeatures1,
    AppCta,
    AppFeatures2,
    AppPricing,
    AppSteps,
    AppTestimonial,
    AppContact,
    AppFooter,
  },
  metaInfo: {
    title: 'Spotless Hungry Crocodile',
  },
}
</script>

<style scoped>
.home-container {
  width: 100%;
  display: flex;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
}
.home-fragment1 {
  display: contents;
}
.home-text1 {
  display: inline-block;
}
.home-fragment2 {
  display: contents;
}
.home-text2 {
  display: inline-block;
}
.home-fragment3 {
  display: contents;
}
.home-text3 {
  display: inline-block;
}
</style>
