// spotless hungry crocodile-react/src/components/pricing.js
import React, { useState } from 'react'

import PropTypes from 'prop-types'

import './pricing.css'

const Pricing = (props) => {
  const [isMonthly, setIsMonthly] = useState(true)
  return (
    <div className="pricing-pricing23 thq-section-padding">
      <div className="pricing-max-width thq-section-max-width">
        <div className="pricing-section-title">
          <span className="pricing-text10 thq-body-small">
            {props.content1}
          </span>
          <div className="pricing-content">
            <h2 className="pricing-text11 thq-heading-2">{props.heading1}</h2>
            <p className="pricing-text12 thq-body-large">{props.content2}</p>
          </div>
        </div>
        <div className="pricing-tabs">
          {isMonthly && (
            <button
              onClick={() => setIsMonthly(true)}
              className="pricing-button10 thq-button-filled thq-button-animated"
            >
              <span className="thq-body-small">Monthly</span>
            </button>
          )}
          {!isMonthly && (
            <button
              onClick={() => setIsMonthly(true)}
              className="pricing-button11 thq-button-animated thq-button-outline"
            >
              <span className="thq-body-small">Monthly</span>
            </button>
          )}
          {!isMonthly && (
            <button
              onClick={() => setIsMonthly(false)}
              className="pricing-button12 thq-button-filled thq-button-animated"
            >
              <span className="thq-body-small">Yearly</span>
            </button>
          )}
          {isMonthly && (
            <button
              onClick={() => setIsMonthly(false)}
              className="pricing-button13 thq-button-animated thq-button-outline"
            >
              <span className="thq-body-small">Yearly</span>
            </button>
          )}
        </div>
        {isMonthly && (
          <div className="pricing-container1">
            <div className="pricing-column1 thq-card">
              <div className="pricing-price10">
                <div className="pricing-price11">
                  <p className="pricing-text17 thq-body-large">{props.plan1}</p>
                  <h3 className="pricing-text18 thq-heading-3">
                    {props.plan1Price}
                  </h3>
                  <p className="thq-body-large">{props.plan1Yearly}</p>
                </div>
                <div className="pricing-list1">
                  <div className="pricing-list-item10">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan1Feature1}
                    </span>
                  </div>
                  <div className="pricing-list-item11">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan1Feature2}
                    </span>
                  </div>
                  <div className="pricing-list-item12">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan1Feature3}
                    </span>
                  </div>
                </div>
              </div>
              <button className="pricing-button14 thq-button-animated thq-button-outline">
                <span className="thq-body-small">{props.plan1Action}</span>
              </button>
            </div>
            <div className="pricing-column2 thq-card">
              <div className="pricing-price12">
                <div className="pricing-price13">
                  <p className="pricing-text24 thq-body-large">{props.plan2}</p>
                  <h3 className="pricing-text25 thq-heading-3">
                    {props.plan2Price}
                  </h3>
                  <p className="thq-body-large">{props.plan2Yearly}</p>
                </div>
                <div className="pricing-list2">
                  <div className="pricing-list-item13">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan2Feature1}
                    </span>
                  </div>
                  <div className="pricing-list-item14">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan2Feature2}
                    </span>
                  </div>
                  <div className="pricing-list-item15">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan2Feature3}
                    </span>
                  </div>
                  <div className="pricing-list-item16">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan2Feature4}
                    </span>
                  </div>
                </div>
              </div>
              <button className="pricing-button15 thq-button-filled thq-button-animated">
                <span className="thq-body-small">{props.plan2Action}</span>
              </button>
            </div>
            <div className="pricing-column3 thq-card">
              <div className="pricing-price14">
                <div className="pricing-price15">
                  <p className="pricing-text32 thq-body-large">{props.plan3}</p>
                  <h3 className="pricing-text33 thq-heading-3">
                    {props.plan3Price}
                  </h3>
                  <p className="thq-body-large">{props.plan3Yearly}</p>
                </div>
                <div className="pricing-list3">
                  <div className="pricing-list-item17">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan3Feature1}
                    </span>
                  </div>
                  <div className="pricing-list-item18">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan3Feature2}
                    </span>
                  </div>
                  <div className="pricing-list-item19">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan3Feature3}
                    </span>
                  </div>
                  <div className="pricing-list-item20">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan3Feature4}
                    </span>
                  </div>
                  <div className="pricing-list-item21">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan3Feature5}
                    </span>
                  </div>
                </div>
              </div>
              <button className="pricing-button16 thq-button-filled thq-button-animated">
                <span className="thq-body-small">{props.plan3Action}</span>
              </button>
            </div>
          </div>
        )}
        {!isMonthly && (
          <div className="pricing-container2">
            <div className="pricing-column4 thq-card">
              <div className="pricing-price16">
                <div className="pricing-price17">
                  <span className="pricing-text41 thq-body-large">
                    {props.plan11}
                  </span>
                  <h3 className="pricing-text42 thq-heading-3">
                    {props.plan1Price1}
                  </h3>
                  <span className="thq-body-large">{props.plan1Yearly1}</span>
                </div>
                <div className="pricing-list4">
                  <div className="pricing-list-item22">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan1Feature11}
                    </span>
                  </div>
                  <div className="pricing-list-item23">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan1Feature21}
                    </span>
                  </div>
                  <div className="pricing-list-item24">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan1Feature31}
                    </span>
                  </div>
                </div>
              </div>
              <button className="pricing-button17 thq-button-animated thq-button-outline">
                <span className="thq-body-small">{props.plan1Action1}</span>
              </button>
            </div>
            <div className="pricing-column5 thq-card">
              <div className="pricing-price18">
                <div className="pricing-price19">
                  <span className="pricing-text48 thq-body-large">
                    {props.plan21}
                  </span>
                  <h3 className="pricing-text49 thq-heading-3">
                    {props.plan2Price1}
                  </h3>
                  <span className="thq-body-large">{props.plan2Yearly1}</span>
                </div>
                <div className="pricing-list5">
                  <div className="pricing-list-item25">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan2Feature11}
                    </span>
                  </div>
                  <div className="pricing-list-item26">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan2Feature21}
                    </span>
                  </div>
                  <div className="pricing-list-item27">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan2Feature31}
                    </span>
                  </div>
                  <div className="pricing-list-item28">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan2Feature41}
                    </span>
                  </div>
                </div>
              </div>
              <button className="pricing-button18 thq-button-filled thq-button-animated">
                <span className="thq-body-small">{props.plan2Action1}</span>
              </button>
            </div>
            <div className="pricing-column6 thq-card">
              <div className="pricing-price20">
                <div className="pricing-price21">
                  <span className="pricing-text56 thq-body-large">
                    {props.plan31}
                  </span>
                  <h3 className="pricing-text57 thq-heading-3">
                    {props.plan3Price1}
                  </h3>
                  <span className="thq-body-large">{props.plan3Yearly1}</span>
                </div>
                <div className="pricing-list6">
                  <div className="pricing-list-item29">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan3Feature11}
                    </span>
                  </div>
                  <div className="pricing-list-item30">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan3Feature21}
                    </span>
                  </div>
                  <div className="pricing-list-item31">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan3Feature31}
                    </span>
                  </div>
                  <div className="pricing-list-item32">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan3Feature41}
                    </span>
                  </div>
                  <div className="pricing-list-item33">
                    <svg viewBox="0 0 1024 1024" className="thq-icon-small">
                      <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
                    </svg>
                    <span className="thq-body-small">
                      {props.plan3Feature51}
                    </span>
                  </div>
                </div>
              </div>
              <button className="pricing-button19 thq-button-filled thq-button-animated">
                <span className="thq-body-small">{props.plan3Action1}</span>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

Pricing.defaultProps = {
  plan3: 'Premium Plan',
  plan31: 'Enterprise plan',
  plan2Feature41: 'Feature text goes here',
  plan3Feature4: 'Feature text goes here',
  plan3Action: 'Sign Up Now',
  content1: 'Choose the perfect plan for you',
  plan1Action: 'Sign Up Now',
  plan1Feature2: '24/7 customer support',
  plan3Price: '$79.99/month',
  plan3Feature2: 'Priority access to specialists',
  plan3Yearly1: 'or $49 monthly',
  plan2Feature11: 'Feature text goes here',
  plan2Feature21: 'Feature text goes here',
  plan1: 'Basic Plan',
  plan21: 'Business plan',
  plan3Yearly: '$799.99/year',
  plan2Feature4: 'Feature text goes here',
  plan2Yearly1: 'or $29 monthly',
  heading1: 'Pricing plan',
  plan1Action1: 'Get started',
  plan3Feature31: 'Feature text goes here',
  plan1Feature21: 'Feature text goes here',
  plan1Feature1: 'Access to basic health monitoring tools',
  plan1Price: '$29.99/month',
  plan2Yearly: '$499.99/year',
  plan1Price1: '$200/yr',
  plan2Price: '$49.99/month',
  plan1Feature11: 'Feature text goes here',
  plan2Feature31: 'Feature text goes here',
  content2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  plan3Feature21: 'Feature text goes here',
  plan2Price1: '$299/yr',
  plan3Feature3: 'Advanced health analytics',
  plan2Action: 'Sign Up Now',
  plan3Feature51: 'Feature text goes here',
  plan1Feature31: 'Feature text goes here',
  plan2Action1: 'Get started',
  plan3Feature1: 'All features of Standard Plan',
  plan3Feature11: 'Feature text goes here',
  plan2Feature3: 'Health data encryption',
  plan11: 'Basic plan',
  plan2: 'Standard Plan',
  plan3Feature41: 'Feature text goes here',
  plan1Feature3: 'Monthly health reports',
  plan2Feature1: 'All features of Basic Plan',
  plan3Feature5: 'Feature text goes here',
  plan3Price1: '$499/yr',
  plan3Action1: 'Get started',
  plan1Yearly1: 'or $20 monthly',
  plan1Yearly: '$299.99/year',
  plan2Feature2: 'Personalized health recommendations',
}

Pricing.propTypes = {
  plan3: PropTypes.string,
  plan31: PropTypes.string,
  plan2Feature41: PropTypes.string,
  plan3Feature4: PropTypes.string,
  plan3Action: PropTypes.string,
  content1: PropTypes.string,
  plan1Action: PropTypes.string,
  plan1Feature2: PropTypes.string,
  plan3Price: PropTypes.string,
  plan3Feature2: PropTypes.string,
  plan3Yearly1: PropTypes.string,
  plan2Feature11: PropTypes.string,
  plan2Feature21: PropTypes.string,
  plan1: PropTypes.string,
  plan21: PropTypes.string,
  plan3Yearly: PropTypes.string,
  plan2Feature4: PropTypes.string,
  plan2Yearly1: PropTypes.string,
  heading1: PropTypes.string,
  plan1Action1: PropTypes.string,
  plan3Feature31: PropTypes.string,
  plan1Feature21: PropTypes.string,
  plan1Feature1: PropTypes.string,
  plan1Price: PropTypes.string,
  plan2Yearly: PropTypes.string,
  plan1Price1: PropTypes.string,
  plan2Price: PropTypes.string,
  plan1Feature11: PropTypes.string,
  plan2Feature31: PropTypes.string,
  content2: PropTypes.string,
  plan3Feature21: PropTypes.string,
  plan2Price1: PropTypes.string,
  plan3Feature3: PropTypes.string,
  plan2Action: PropTypes.string,
  plan3Feature51: PropTypes.string,
  plan1Feature31: PropTypes.string,
  plan2Action1: PropTypes.string,
  plan3Feature1: PropTypes.string,
  plan3Feature11: PropTypes.string,
  plan2Feature3: PropTypes.string,
  plan11: PropTypes.string,
  plan2: PropTypes.string,
  plan3Feature41: PropTypes.string,
  plan1Feature3: PropTypes.string,
  plan2Feature1: PropTypes.string,
  plan3Feature5: PropTypes.string,
  plan3Price1: PropTypes.string,
  plan3Action1: PropTypes.string,
  plan1Yearly1: PropTypes.string,
  plan1Yearly: PropTypes.string,
  plan2Feature2: PropTypes.string,
}

export default Pricing

// spotless hungry crocodile-angular/src/app/components/pricing/pricing.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-pricing',
  templateUrl: 'pricing.component.html',
  styleUrls: ['pricing.component.css'],
})
export class Pricing {
  @Input()
  plan3: string = 'Premium Plan'
  @Input()
  plan31: string = 'Enterprise plan'
  @Input()
  plan2Feature41: string = 'Feature text goes here'
  @Input()
  plan3Feature4: string = 'Feature text goes here'
  @Input()
  plan3Action: string = 'Sign Up Now'
  @Input()
  content1: string = 'Choose the perfect plan for you'
  @Input()
  plan1Action: string = 'Sign Up Now'
  @Input()
  plan1Feature2: string = '24/7 customer support'
  @Input()
  plan3Price: string = '$79.99/month'
  @Input()
  plan3Feature2: string = 'Priority access to specialists'
  @Input()
  plan3Yearly1: string = 'or $49 monthly'
  @Input()
  plan2Feature11: string = 'Feature text goes here'
  @Input()
  plan2Feature21: string = 'Feature text goes here'
  @Input()
  plan1: string = 'Basic Plan'
  @Input()
  plan21: string = 'Business plan'
  @Input()
  plan3Yearly: string = '$799.99/year'
  @Input()
  plan2Feature4: string = 'Feature text goes here'
  @Input()
  plan2Yearly1: string = 'or $29 monthly'
  @Input()
  heading1: string = 'Pricing plan'
  @Input()
  plan1Action1: string = 'Get started'
  @Input()
  plan3Feature31: string = 'Feature text goes here'
  @Input()
  plan1Feature21: string = 'Feature text goes here'
  @Input()
  plan1Feature1: string = 'Access to basic health monitoring tools'
  @Input()
  plan1Price: string = '$29.99/month'
  @Input()
  plan2Yearly: string = '$499.99/year'
  @Input()
  plan1Price1: string = '$200/yr'
  @Input()
  plan2Price: string = '$49.99/month'
  @Input()
  plan1Feature11: string = 'Feature text goes here'
  @Input()
  plan2Feature31: string = 'Feature text goes here'
  @Input()
  content2: string = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
  @Input()
  plan3Feature21: string = 'Feature text goes here'
  @Input()
  plan2Price1: string = '$299/yr'
  @Input()
  plan3Feature3: string = 'Advanced health analytics'
  @Input()
  plan2Action: string = 'Sign Up Now'
  @Input()
  plan3Feature51: string = 'Feature text goes here'
  @Input()
  plan1Feature31: string = 'Feature text goes here'
  @Input()
  plan2Action1: string = 'Get started'
  @Input()
  plan3Feature1: string = 'All features of Standard Plan'
  @Input()
  plan3Feature11: string = 'Feature text goes here'
  @Input()
  plan2Feature3: string = 'Health data encryption'
  @Input()
  plan11: string = 'Basic plan'
  @Input()
  plan2: string = 'Standard Plan'
  @Input()
  plan3Feature41: string = 'Feature text goes here'
  @Input()
  plan1Feature3: string = 'Monthly health reports'
  @Input()
  plan2Feature1: string = 'All features of Basic Plan'
  @Input()
  plan3Feature5: string = 'Feature text goes here'
  @Input()
  plan3Price1: string = '$499/yr'
  @Input()
  plan3Action1: string = 'Get started'
  @Input()
  plan1Yearly1: string = 'or $20 monthly'
  @Input()
  plan1Yearly: string = '$299.99/year'
  @Input()
  plan2Feature2: string = 'Personalized health recommendations'
  isMonthly: boolean = true
  constructor() {}
}

<div class="pricing-pricing23 thq-section-padding">
  <div class="pricing-max-width thq-section-max-width">
    <div class="pricing-section-title">
      <span class="pricing-text10 thq-body-small">{{ content1 }}</span>
      <div class="pricing-content">
        <h2 class="pricing-text11 thq-heading-2">{{ heading1 }}</h2>
        <p class="pricing-text12 thq-body-large">{{ content2 }}</p>
      </div>
    </div>
    <div class="pricing-tabs">
      <button
        (click)="isMonthly = true"
        *ngIf="isMonthly"
        class="pricing-button10 thq-button-filled thq-button-animated"
      >
        <span class="thq-body-small">Monthly</span>
      </button>
      <button
        (click)="isMonthly = true"
        *ngIf="!isMonthly"
        class="pricing-button11 thq-button-animated thq-button-outline"
      >
        <span class="thq-body-small">Monthly</span>
      </button>
      <button
        (click)="isMonthly = false"
        *ngIf="!isMonthly"
        class="pricing-button12 thq-button-filled thq-button-animated"
      >
        <span class="thq-body-small">Yearly</span>
      </button>
      <button
        (click)="isMonthly = false"
        *ngIf="isMonthly"
        class="pricing-button13 thq-button-animated thq-button-outline"
      >
        <span class="thq-body-small">Yearly</span>
      </button>
    </div>
    <div *ngIf="isMonthly" class="pricing-container1">
      <div class="pricing-column1 thq-card">
        <div class="pricing-price10">
          <div class="pricing-price11">
            <p class="pricing-text17 thq-body-large">{{ plan1 }}</p>
            <h3 class="pricing-text18 thq-heading-3">{{ plan1Price }}</h3>
            <p class="thq-body-large">{{ plan1Yearly }}</p>
          </div>
          <div class="pricing-list1">
            <div class="pricing-list-item10">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan1Feature1 }}</span>
            </div>
            <div class="pricing-list-item11">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan1Feature2 }}</span>
            </div>
            <div class="pricing-list-item12">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan1Feature3 }}</span>
            </div>
          </div>
        </div>
        <button class="pricing-button14 thq-button-animated thq-button-outline">
          <span class="thq-body-small">{{ plan1Action }}</span>
        </button>
      </div>
      <div class="pricing-column2 thq-card">
        <div class="pricing-price12">
          <div class="pricing-price13">
            <p class="pricing-text24 thq-body-large">{{ plan2 }}</p>
            <h3 class="pricing-text25 thq-heading-3">{{ plan2Price }}</h3>
            <p class="thq-body-large">{{ plan2Yearly }}</p>
          </div>
          <div class="pricing-list2">
            <div class="pricing-list-item13">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan2Feature1 }}</span>
            </div>
            <div class="pricing-list-item14">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan2Feature2 }}</span>
            </div>
            <div class="pricing-list-item15">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan2Feature3 }}</span>
            </div>
            <div class="pricing-list-item16">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan2Feature4 }}</span>
            </div>
          </div>
        </div>
        <button class="pricing-button15 thq-button-filled thq-button-animated">
          <span class="thq-body-small">{{ plan2Action }}</span>
        </button>
      </div>
      <div class="pricing-column3 thq-card">
        <div class="pricing-price14">
          <div class="pricing-price15">
            <p class="pricing-text32 thq-body-large">{{ plan3 }}</p>
            <h3 class="pricing-text33 thq-heading-3">{{ plan3Price }}</h3>
            <p class="thq-body-large">{{ plan3Yearly }}</p>
          </div>
          <div class="pricing-list3">
            <div class="pricing-list-item17">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan3Feature1 }}</span>
            </div>
            <div class="pricing-list-item18">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan3Feature2 }}</span>
            </div>
            <div class="pricing-list-item19">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan3Feature3 }}</span>
            </div>
            <div class="pricing-list-item20">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan3Feature4 }}</span>
            </div>
            <div class="pricing-list-item21">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan3Feature5 }}</span>
            </div>
          </div>
        </div>
        <button class="pricing-button16 thq-button-filled thq-button-animated">
          <span class="thq-body-small">{{ plan3Action }}</span>
        </button>
      </div>
    </div>
    <div *ngIf="!isMonthly" class="pricing-container2">
      <div class="pricing-column4 thq-card">
        <div class="pricing-price16">
          <div class="pricing-price17">
            <span class="pricing-text41 thq-body-large">{{ plan11 }}</span>
            <h3 class="pricing-text42 thq-heading-3">{{ plan1Price1 }}</h3>
            <span class="thq-body-large">{{ plan1Yearly1 }}</span>
          </div>
          <div class="pricing-list4">
            <div class="pricing-list-item22">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan1Feature11 }}</span>
            </div>
            <div class="pricing-list-item23">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan1Feature21 }}</span>
            </div>
            <div class="pricing-list-item24">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan1Feature31 }}</span>
            </div>
          </div>
        </div>
        <button class="pricing-button17 thq-button-animated thq-button-outline">
          <span class="thq-body-small">{{ plan1Action1 }}</span>
        </button>
      </div>
      <div class="pricing-column5 thq-card">
        <div class="pricing-price18">
          <div class="pricing-price19">
            <span class="pricing-text48 thq-body-large">{{ plan21 }}</span>
            <h3 class="pricing-text49 thq-heading-3">{{ plan2Price1 }}</h3>
            <span class="thq-body-large">{{ plan2Yearly1 }}</span>
          </div>
          <div class="pricing-list5">
            <div class="pricing-list-item25">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan2Feature11 }}</span>
            </div>
            <div class="pricing-list-item26">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan2Feature21 }}</span>
            </div>
            <div class="pricing-list-item27">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan2Feature31 }}</span>
            </div>
            <div class="pricing-list-item28">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan2Feature41 }}</span>
            </div>
          </div>
        </div>
        <button class="pricing-button18 thq-button-filled thq-button-animated">
          <span class="thq-body-small">{{ plan2Action1 }}</span>
        </button>
      </div>
      <div class="pricing-column6 thq-card">
        <div class="pricing-price20">
          <div class="pricing-price21">
            <span class="pricing-text56 thq-body-large">{{ plan31 }}</span>
            <h3 class="pricing-text57 thq-heading-3">{{ plan3Price1 }}</h3>
            <span class="thq-body-large">{{ plan3Yearly1 }}</span>
          </div>
          <div class="pricing-list6">
            <div class="pricing-list-item29">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan3Feature11 }}</span>
            </div>
            <div class="pricing-list-item30">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan3Feature21 }}</span>
            </div>
            <div class="pricing-list-item31">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan3Feature31 }}</span>
            </div>
            <div class="pricing-list-item32">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan3Feature41 }}</span>
            </div>
            <div class="pricing-list-item33">
              <svg viewBox="0 0 1024 1024" class="thq-icon-small">
                <path d="M384 690l452-452 60 60-512 512-238-238 60-60z"></path>
              </svg>
              <span class="thq-body-small">{{ plan3Feature51 }}</span>
            </div>
          </div>
        </div>
        <button class="pricing-button19 thq-button-filled thq-button-animated">
          <span class="thq-body-small">{{ plan3Action1 }}</span>
        </button>
      </div>
    </div>
  </div>
</div>
